### ISSUE TITLE
How does the epsilon work in svm_loss_vectorized?

### ISSUE THREAD

**Issue by buaaMars** [xiezhq-hermann/cs231n-2017#1]
Your work is extraordinary. But I am confused with the epsilon in
https://github.com/xiezhq-hermann/cs231n-2017/blob/master/assignment1/cs231n/classifiers/linear_svm.py

I try to replace the epsilon in line 102 with 0 but get a wrong result, which proves your code is right. But I cannot figure out why there should be the epsilon.
I will appreciate it if you could give me an explanation.

**Comment by xiezhq-hermann** [comment]
Github didn't notice me about this issue because I set the repo to "no longer in maintenance", hope it's not too late for you to get the reply.
The epsilon is common in scientific computing, since the general methods (like IEEE 754) we take to represent the floating point numbers are not exactly correct (with very very small error). This fact should be regarded while the task is very numeric sensitive. In details, if you set the epsilon here to be 0, you might probably treat two equivalent float pointing number as different, the small error will be amplified to destroy the correctness of the algorithm itself.
